#################################
# dev01111 classic proxy system #
# Copyright (C) dev01111 2022   #
#################################
# This code contains actions    #
# outside of dev01111s repos.   #
# This is     completely the    #
# official action.              #
#################################


name: "dev01111 proxy system"
on: 
  push:
    paths:
      - '**.dwnld'
  workflow_dispatch:
      
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Download
        run: |
          curl -LO "https://web.archive.org/web/20250918145206id_/https://musical-artifacts.com/artifacts/6022/SM64SF_V3.sf2"
      - name: Upload File
        uses: actions/upload-artifact@v6
        with:
          name: "File"
          path: "SM64SF_V3.sf2"
